CREATE INDEX `audit_logs_user_id_created_at_idx` ON `audit_logs` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `audit_logs_nas_id_created_at_idx` ON `audit_logs` (`nasId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `bank_transfer_requests_user_id_submitted_at_idx` ON `bank_transfer_requests` (`userId`,`submittedAt`);--> statement-breakpoint
CREATE INDEX `bank_transfer_requests_status_idx` ON `bank_transfer_requests` (`status`);--> statement-breakpoint
CREATE INDEX `card_batches_created_by_idx` ON `card_batches` (`createdBy`);--> statement-breakpoint
CREATE INDEX `card_batches_reseller_id_idx` ON `card_batches` (`resellerId`);--> statement-breakpoint
CREATE INDEX `card_batches_created_at_idx` ON `card_batches` (`createdAt`);--> statement-breakpoint
CREATE INDEX `chat_messages_ticket_id_created_at_idx` ON `chat_messages` (`ticketId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `internal_notif_user_id_is_read_created_at_idx` ON `internal_notifications` (`userId`,`isRead`,`createdAt`);--> statement-breakpoint
CREATE INDEX `invoices_user_id_created_at_idx` ON `invoices` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `invoices_status_idx` ON `invoices` (`status`);--> statement-breakpoint
CREATE INDEX `invoices_user_id_status_idx` ON `invoices` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `nas_owner_id_idx` ON `nas` (`ownerId`);--> statement-breakpoint
CREATE INDEX `nas_status_idx` ON `nas` (`status`);--> statement-breakpoint
CREATE INDEX `router_down_log_router_id_owner_detected_at_idx` ON `network_router_down_log` (`routerId`,`ownerId`,`detectedAt`);--> statement-breakpoint
CREATE INDEX `network_routers_owner_id_idx` ON `network_routers` (`ownerId`);--> statement-breakpoint
CREATE INDEX `network_routers_owner_nas_idx` ON `network_routers` (`ownerId`,`nasId`);--> statement-breakpoint
CREATE INDEX `notifications_user_id_is_read_idx` ON `notifications` (`userId`,`isRead`);--> statement-breakpoint
CREATE INDEX `notifications_created_at_idx` ON `notifications` (`createdAt`);--> statement-breakpoint
CREATE INDEX `plans_owner_id_idx` ON `plans` (`ownerId`);--> statement-breakpoint
CREATE INDEX `radhuntgroup_nasipaddress_idx` ON `radhuntgroup` (`nasipaddress`);--> statement-breakpoint
CREATE INDEX `radhuntgroup_group_nas_idx` ON `radhuntgroup` (`groupname`,`nasipaddress`);--> statement-breakpoint
CREATE INDEX `radpostauth_username_idx` ON `radpostauth` (`username`);--> statement-breakpoint
CREATE INDEX `radpostauth_authdate_idx` ON `radpostauth` (`authdate`);--> statement-breakpoint
CREATE INDEX `radpostauth_reply_authdate_idx` ON `radpostauth` (`reply`,`authdate`);--> statement-breakpoint
CREATE INDEX `radusergroup_username_idx` ON `radusergroup` (`username`);--> statement-breakpoint
CREATE INDEX `radusergroup_username_group_idx` ON `radusergroup` (`username`,`groupname`);--> statement-breakpoint
CREATE INDEX `sms_balance_log_owner_id_created_at_idx` ON `sms_balance_log` (`ownerId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `sms_contacts_owner_id_created_at_idx` ON `sms_contacts` (`ownerId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `sms_logs_user_id_created_at_idx` ON `sms_logs` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `sms_send_log_owner_id_created_at_idx` ON `sms_send_log` (`ownerId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `subscriber_subs_subscriber_id_created_at_idx` ON `subscriber_subscriptions` (`subscriberId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `subscribers_owner_id_idx` ON `subscribers` (`ownerId`);--> statement-breakpoint
CREATE INDEX `subscribers_created_by_idx` ON `subscribers` (`createdBy`);--> statement-breakpoint
CREATE INDEX `subscribers_status_idx` ON `subscribers` (`status`);--> statement-breakpoint
CREATE INDEX `subscribers_status_end_date_idx` ON `subscribers` (`status`,`subscriptionEndDate`);--> statement-breakpoint
CREATE INDEX `support_tickets_user_id_created_at_idx` ON `support_tickets` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `support_tickets_status_idx` ON `support_tickets` (`status`);--> statement-breakpoint
CREATE INDEX `transactions_user_id_created_at_idx` ON `transactions` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `transactions_wallet_id_idx` ON `transactions` (`walletId`);--> statement-breakpoint
CREATE INDEX `users_role_idx` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `users_tenant_id_idx` ON `users` (`tenantId`);--> statement-breakpoint
CREATE INDEX `users_reseller_id_idx` ON `users` (`resellerId`);--> statement-breakpoint
CREATE INDEX `users_role_billing_status_idx` ON `users` (`role`,`billingStatus`);--> statement-breakpoint
CREATE INDEX `vpn_logs_nas_id_created_at_idx` ON `vpn_logs` (`nasId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `wallet_ledger_user_id_created_at_idx` ON `wallet_ledger` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `wallet_ledger_user_id_type_idx` ON `wallet_ledger` (`userId`,`type`);