CREATE TABLE IF NOT EXISTS `port_forwardings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ownerId` INT NOT NULL,
  `nasId` INT NOT NULL,
  `networkRouterId` INT NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  `targetIp` VARCHAR(45) NOT NULL,
  `targetPort` INT NOT NULL,
  `vpnTunnelIp` VARCHAR(45) NOT NULL,
  `externalPort` INT NOT NULL,
  `ingressPort` INT NOT NULL,
  `protocol` ENUM('tcp') NOT NULL DEFAULT 'tcp',
  `allowedCidrs` JSON NOT NULL,
  `status` ENUM('pending','active','disabled','error') NOT NULL DEFAULT 'pending',
  `lastError` TEXT NULL,
  `enabledAt` TIMESTAMP NULL,
  `disabledAt` TIMESTAMP NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `port_forwardings_external_port_uniq` (`externalPort`),
  UNIQUE KEY `port_forwardings_nas_ingress_port_uniq` (`nasId`, `ingressPort`),
  KEY `port_forwardings_owner_idx` (`ownerId`),
  KEY `port_forwardings_owner_nas_idx` (`ownerId`, `nasId`),
  KEY `port_forwardings_router_idx` (`networkRouterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
