CREATE TABLE IF NOT EXISTS `management_vpn_sessions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `ownerId` int NOT NULL,
  `nasId` int NOT NULL,
  `networkRouterId` int NOT NULL,
  `createdBy` int NOT NULL,
  `label` varchar(100) NOT NULL,
  `clientAddress` varchar(45) NOT NULL,
  `virtualTargetIp` varchar(45) NOT NULL,
  `targetIp` varchar(45) NOT NULL,
  `targetPorts` json NOT NULL,
  `allowedProtocols` json NOT NULL,
  `clientPublicKey` varchar(128),
  `sessionToken` varchar(64) NOT NULL,
  `status` enum('pending','active','suspended','revoked','expired','error') NOT NULL DEFAULT 'pending',
  `expiresAt` timestamp NOT NULL,
  `startedAt` timestamp NULL,
  `endedAt` timestamp NULL,
  `lastError` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `management_vpn_sessions_id` PRIMARY KEY(`id`),
  CONSTRAINT `management_vpn_sessions_token_unique` UNIQUE(`sessionToken`),
  CONSTRAINT `management_vpn_virtual_target_uniq` UNIQUE(`nasId`,`virtualTargetIp`),
  INDEX `management_vpn_owner_idx` (`ownerId`),
  INDEX `management_vpn_nas_idx` (`nasId`),
  INDEX `management_vpn_status_expiry_idx` (`status`,`expiresAt`)
);
